export enum Role {
  ADMIN = 'ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  TA = 'TA',
}

export enum CourseRole {
  INSTRUCTOR = 'INSTRUCTOR',
  TA = 'TA',
}

export enum Semester {
  SPRING = 'SPRING',
  SUMMER = 'SUMMER',
  FALL = 'FALL',
  WINTER = 'WINTER',
}

export enum SessionCategory {
  GRADING = 'GRADING',
  OFFICE_HOURS = 'OFFICE_HOURS',
  LAB_SUPPORT = 'LAB_SUPPORT',
  PREP = 'PREP',
  MEETING = 'MEETING',
  OTHER = 'OTHER',
}

export enum SessionMode {
  LIVE = 'LIVE',
  ASYNC = 'ASYNC',
}

export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  AUTO_STOPPED = 'AUTO_STOPPED',
}

export enum EventType {
  START = 'START',
  PAUSE = 'PAUSE',
  RESUME = 'RESUME',
  STOP = 'STOP',
  AUTO_STOP = 'AUTO_STOP',
  SCREENSHOT = 'SCREENSHOT',
}

export enum SubmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
}

export enum AuditAction {
  SESSION_START = 'SESSION_START',
  SESSION_STOP = 'SESSION_STOP',
  SESSION_AUTO_STOP = 'SESSION_AUTO_STOP',
  SUBMISSION_SUBMIT = 'SUBMISSION_SUBMIT',
  SUBMISSION_APPROVE = 'SUBMISSION_APPROVE',
  SUBMISSION_REJECT = 'SUBMISSION_REJECT',
  HOURS_EDIT = 'HOURS_EDIT',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  COURSE_CREATE = 'COURSE_CREATE',
  COURSE_UPDATE = 'COURSE_UPDATE',
  ASSIGNMENT_CREATE = 'ASSIGNMENT_CREATE',
  ASSIGNMENT_UPDATE = 'ASSIGNMENT_UPDATE',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}
